# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/')),
                ('bio', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
    ]
