# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_prof',
        ),
    ]
