# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
