# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0006_auto_20190601_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
